# Generated by Django 4.0.4 on 2022-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_content',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_design',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_usability',
            field=models.FloatField(default=0),
        ),
    ]
